package org.napile.compiler.bytecode;

public class ConvertTest extends ConvertTestCase
{
	public void test$napile_annotation_Annotation() {}
	public void test$napile_annotation_DefaultValue() {}
	public void test$napile_annotation_Deprecated() {}
	public void test$napile_annotation_Equality() {}
	public void test$napile_annotation_Extension() {}
	public void test$napile_annotation_Immutable() {}
	public void test$napile_annotation_ImmutableTarget() {}
	public void test$napile_annotation_InheritImmutable() {}
	public void test$napile_annotation_Lazy() {}
	public void test$napile_annotation_LazyType() {}
	public void test$napile_annotation_Repeatable() {}
	public void test$napile_annotation_VarArgs() {}
	public void test$napile_asm_AsmUtil() {}
	public void test$napile_asm_members_AsmAnnotation() {}
	public void test$napile_asm_members_AsmClass() {}
	public void test$napile_asm_members_AsmType() {}
	public void test$napile_asm_members_AsmTypeConstructor() {}
	public void test$napile_asm_members_typeConstructor_AsmClassType() {}
	public void test$napile_asm_members_typeConstructor_AsmTypeParameterType() {}
	public void test$napile_collection_ArrayList() {}
	public void test$napile_collection_Collection() {}
	public void test$napile_collection_HashMap() {}
	public void test$napile_collection_Iterable() {}
	public void test$napile_collection_IterableUtil() {}
	public void test$napile_collection_Iterator() {}
	public void test$napile_collection_List() {}
	public void test$napile_collection_ListIterator() {}
	public void test$napile_collection_Map() {}
	public void test$napile_collection_Set() {}
	public void test$napile_collection_Sizeable() {}
	public void test$napile_condition_CompareResult() {}
	public void test$napile_condition_Condition() {}
	public void test$napile_io_Closeable() {}
	public void test$napile_io_File() {}
	public void test$napile_io_FileDescriptor() {}
	public void test$napile_io_FileInputStream() {}
	public void test$napile_io_FileNotFoundException() {}
	public void test$napile_io_FileOutputStream() {}
	public void test$napile_io_Flushable() {}
	public void test$napile_io_InputStream() {}
	public void test$napile_io_IOException() {}
	public void test$napile_io_IoUtil() {}
	public void test$napile_io_NativeConsole() {}
	public void test$napile_io_OutputStream() {}
	public void test$napile_io_SecurityManager() {}
	public void test$napile_lang_AnonymContext() {}
	public void test$napile_lang_Any() {}
	public void test$napile_lang_Application() {}
	public void test$napile_lang_Array() {}
	public void test$napile_lang_ArrayIndexOutOfBoundsException() {}
	public void test$napile_lang_ArrayIterator() {}
	public void test$napile_lang_ArrayUtil() {}
	public void test$napile_lang_AssertionError() {}
	public void test$napile_lang_Bool() {}
	public void test$napile_lang_Byte() {}
	public void test$napile_lang_Char() {}
	public void test$napile_lang_ClassCastException() {}
	public void test$napile_lang_Double() {}
	public void test$napile_lang_Error() {}
	public void test$napile_lang_Exception() {}
	public void test$napile_lang_Float() {}
	public void test$napile_lang_IllegalArgumentException() {}
	public void test$napile_lang_IllegalStateException() {}
	public void test$napile_lang_IndexOutOfBoundsException() {}
	public void test$napile_lang_Int() {}
	public void test$napile_lang_Invalid() {}
	public void test$napile_lang_Long() {}
	public void test$napile_lang_Math() {}
	public void test$napile_lang_Multi() {}
	public void test$napile_lang_Null() {}
	public void test$napile_lang_NullPointerException() {}
	public void test$napile_lang_Number() {}
	public void test$napile_lang_Runtime() {}
	public void test$napile_lang_Short() {}
	public void test$napile_lang_StackTraceElement() {}
	public void test$napile_lang_String() {}
	public void test$napile_lang_StringBuilder() {}
	public void test$napile_lang_Thread() {}
	public void test$napile_lang_ThreadGroup() {}
	public void test$napile_lang_ThreadState() {}
	public void test$napile_lang_UnsupportedOperationException() {}
	public void test$napile_logging_impl_handlers_CombinedLoggingHandler() {}
	public void test$napile_logging_impl_handlers_ConsoleLoggingHandler() {}
	public void test$napile_logging_impl_LoggerImpl() {}
	public void test$napile_logging_Logger() {}
	public void test$napile_logging_LoggingHandler() {}
	public void test$napile_logging_LoggingHandlerDescriptor() {}
	public void test$napile_logging_LoggingLevel() {}
	public void test$napile_logging_LoggingMessage() {}
	public void test$napile_module_extension_Extension() {}
	public void test$napile_module_extension_ExtensionPoint() {}
	public void test$napile_module_extension_ExtensionPointName() {}
	public void test$napile_module_extension_Extensions() {}
	public void test$napile_module_Module() {}
	public void test$napile_nio_channels_FileChannel() {}
	public void test$napile_reflect_AnnotationOwner() {}
	public void test$napile_reflect_CallParameter() {}
	public void test$napile_reflect_Class() {}
	public void test$napile_reflect_ClassNotFoundException() {}
	public void test$napile_reflect_Constructor() {}
	public void test$napile_reflect_Macro() {}
	public void test$napile_reflect_Member() {}
	public void test$napile_reflect_Method() {}
	public void test$napile_reflect_MethodLike() {}
	public void test$napile_reflect_Modifier() {}
	public void test$napile_reflect_ReflectUtil() {}
	public void test$napile_reflect_Type() {}
	public void test$napile_reflect_Variable() {}
	public void test$napile_resource_ResourceBundle() {}
	public void test$napile_testing_Before() {}
	public void test$napile_testing_Test() {}
	public void test$napile_ui_Button() {}
	public void test$napile_ui_ClickEvent() {}
	public void test$napile_ui_CmykColor() {}
	public void test$napile_ui_Color() {}
	public void test$napile_ui_Component() {}
	public void test$napile_ui_RgbColor() {}
	public void test$napile_ui_RootPanel() {}
	public void test$napile_util_EqualUtil() {}
	public void test$napile_util_listeners_ListenerHolder() {}
	public void test$napile_util_ModuleUtil() {}
	public void test$napile_util_TypeUtil() {}
	public void test$napile_web_WebPage() {}
	public void test$napile_web_WebSession() {}
	public void test$org_apache_harmony_luni_platform_IFileSystem() {}
	public void test$org_apache_harmony_luni_platform_OSFileSystem() {}
	public void test$org_apache_harmony_luni_platform_Platform() {}
	public void test$org_apache_harmony_nio_FileChannelFactory() {}
	public void test$org_napile_vm_MainCaller() {}
	public void test$org_napile_vm_VmStartupError() {}
	public void test$xml_annotation_DomAttribute() {}
	public void test$xml_annotation_DomElement() {}
	public void test$xml_impl_XmlDocumentImpl() {}
	public void test$xml_impl_XmlElementHolderImpl() {}
	public void test$xml_impl_XmlElementImpl() {}
	public void test$xml_XmlDocument() {}
	public void test$xml_XmlElement() {}
	public void test$xml_XmlElementHolder() {}
	public void test$xml_XmlNode() {}
}