/*
 * Copyright 2010-2012 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.napile.compiler.di;

import java.util.List;

import javax.annotation.PreDestroy;

import org.jetbrains.annotations.NotNull;
import org.napile.compiler.lang.resolve.BindingContext;
import org.napile.compiler.lang.resolve.BindingTrace;
import org.napile.compiler.psi.NapileFile;
import com.intellij.openapi.project.Project;

/* This file is generated by org.jetbrains.jet.di.AllInjectorsGenerator. DO NOT EDIT! */
public class InjectorForJvmCodegen
{
	private final BindingTrace bindingTrace;
	private final List<NapileFile> listOfNapileFile;
	private final Project project;
	private BindingContext bindingContext;

	public InjectorForJvmCodegen(@NotNull BindingTrace bindingTrace,@NotNull List<NapileFile> listOfNapileFile,@NotNull Project project)
	{
		this.bindingTrace = bindingTrace;
		this.listOfNapileFile = listOfNapileFile;
		this.project = project;
		this.bindingContext = bindingTrace.getBindingContext();

	}

	@PreDestroy
	public void destroy()
	{
	}

	public BindingTrace getBindingTrace()
	{
		return this.bindingTrace;
	}

	public BindingContext getBindingContext()
	{
		return this.bindingContext;
	}

}
