/*
 * Copyright 2010-2012 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.jetbrains.jet.di;

import org.napile.compiler.lang.resolve.BindingContext;
import java.util.List;
import org.napile.compiler.lang.psi.NapileFile;
import com.intellij.openapi.project.Project;
import org.jetbrains.annotations.NotNull;
import javax.annotation.PreDestroy;

/* This file is generated by org.jetbrains.jet.di.AllInjectorsGenerator. DO NOT EDIT! */
public class InjectorForJvmCodegen {

    private final BindingContext bindingContext;
    private final List<NapileFile> listOfNapileFile;
    private final Project project;

    public InjectorForJvmCodegen(
        @NotNull BindingContext bindingContext,
        @NotNull List<NapileFile> listOfNapileFile,
        @NotNull Project project
    ) {
        this.bindingContext = bindingContext;
        this.listOfNapileFile = listOfNapileFile;
        this.project = project;

    }

    @PreDestroy
    public void destroy() {
    }

}
