/* The following code was generated by JFlex 1.4.3 on 01.09.13 0:36 */

 package org.napile.compiler.lang.lexer;

import java.util.Stack;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.TokenType;
import com.intellij.psi.tree.IElementType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 01.09.13 0:36 from the specification file
 * <tt>F:/github.com/napile/napile.compiler.core/frontend.source/src/main/java/org/napile/compiler/lang/lexer/_NapileLexer.flex</tt>
 */
class _NapileLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int BLOCK_COMMENT = 4;
  public static final int YYINITIAL = 0;
  public static final int DOC_COMMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\7\1\0\1\3\23\0\1\3\1\51\1\0\1\53"+
    "\1\0\1\64\1\60\1\17\1\71\1\72\1\22\1\56\1\74\1\15"+
    "\1\13\1\6\1\10\11\1\1\62\1\73\1\52\1\57\1\54\1\55"+
    "\1\75\1\2\1\12\2\2\1\14\1\2\11\4\1\16\7\4\1\11"+
    "\2\4\1\65\1\20\1\66\1\63\1\4\1\0\1\33\1\44\1\24"+
    "\1\50\1\31\1\47\1\35\1\42\1\30\1\4\1\34\1\43\1\40"+
    "\1\26\1\25\1\32\1\4\1\36\1\45\1\27\1\21\1\46\1\41"+
    "\1\11\1\37\1\4\1\67\1\61\1\70\1\23\53\0\1\4\12\0"+
    "\1\4\4\0\1\4\5\0\27\4\1\0\37\4\1\0\u013f\4\31\0"+
    "\162\4\4\0\14\4\16\0\5\4\11\0\1\4\213\0\1\4\13\0"+
    "\1\4\1\0\3\4\1\0\1\4\1\0\24\4\1\0\54\4\1\0"+
    "\46\4\1\0\5\4\4\0\202\4\10\0\105\4\1\0\46\4\2\0"+
    "\2\4\6\0\20\4\41\0\46\4\2\0\1\4\7\0\47\4\110\0"+
    "\33\4\5\0\3\4\56\0\32\4\5\0\13\4\25\0\12\5\4\0"+
    "\2\4\1\0\143\4\1\0\1\4\17\0\2\4\7\0\2\4\12\5"+
    "\3\4\2\0\1\4\20\0\1\4\1\0\36\4\35\0\3\4\60\0"+
    "\46\4\13\0\1\4\u0152\0\66\4\3\0\1\4\22\0\1\4\7\0"+
    "\12\4\4\0\12\5\25\0\10\4\2\0\2\4\2\0\26\4\1\0"+
    "\7\4\1\0\1\4\3\0\4\4\3\0\1\4\36\0\2\4\1\0"+
    "\3\4\4\0\12\5\2\4\23\0\6\4\4\0\2\4\2\0\26\4"+
    "\1\0\7\4\1\0\2\4\1\0\2\4\1\0\2\4\37\0\4\4"+
    "\1\0\1\4\7\0\12\5\2\0\3\4\20\0\11\4\1\0\3\4"+
    "\1\0\26\4\1\0\7\4\1\0\2\4\1\0\5\4\3\0\1\4"+
    "\22\0\1\4\17\0\2\4\4\0\12\5\25\0\10\4\2\0\2\4"+
    "\2\0\26\4\1\0\7\4\1\0\2\4\1\0\5\4\3\0\1\4"+
    "\36\0\2\4\1\0\3\4\4\0\12\5\1\0\1\4\21\0\1\4"+
    "\1\0\6\4\3\0\3\4\1\0\4\4\3\0\2\4\1\0\1\4"+
    "\1\0\2\4\3\0\2\4\3\0\3\4\3\0\10\4\1\0\3\4"+
    "\55\0\11\5\25\0\10\4\1\0\3\4\1\0\27\4\1\0\12\4"+
    "\1\0\5\4\46\0\2\4\4\0\12\5\25\0\10\4\1\0\3\4"+
    "\1\0\27\4\1\0\12\4\1\0\5\4\3\0\1\4\40\0\1\4"+
    "\1\0\2\4\4\0\12\5\25\0\10\4\1\0\3\4\1\0\27\4"+
    "\1\0\20\4\46\0\2\4\4\0\12\5\25\0\22\4\3\0\30\4"+
    "\1\0\11\4\1\0\1\4\2\0\7\4\72\0\60\4\1\0\2\4"+
    "\14\0\7\4\11\0\12\5\47\0\2\4\1\0\1\4\2\0\2\4"+
    "\1\0\1\4\2\0\1\4\6\0\4\4\1\0\7\4\1\0\3\4"+
    "\1\0\1\4\1\0\1\4\2\0\2\4\1\0\4\4\1\0\2\4"+
    "\11\0\1\4\2\0\5\4\1\0\1\4\11\0\12\5\2\0\2\4"+
    "\42\0\1\4\37\0\12\5\26\0\10\4\1\0\42\4\35\0\4\4"+
    "\164\0\42\4\1\0\5\4\1\0\2\4\25\0\12\5\6\0\6\4"+
    "\112\0\46\4\12\0\51\4\7\0\132\4\5\0\104\4\5\0\122\4"+
    "\6\0\7\4\1\0\77\4\1\0\1\4\1\0\4\4\2\0\7\4"+
    "\1\0\1\4\1\0\4\4\2\0\47\4\1\0\1\4\1\0\4\4"+
    "\2\0\37\4\1\0\1\4\1\0\4\4\2\0\7\4\1\0\1\4"+
    "\1\0\4\4\2\0\7\4\1\0\7\4\1\0\27\4\1\0\37\4"+
    "\1\0\1\4\1\0\4\4\2\0\7\4\1\0\47\4\1\0\23\4"+
    "\16\0\11\5\56\0\125\4\14\0\u026c\4\2\0\10\4\12\0\32\4"+
    "\5\0\113\4\25\0\15\4\1\0\4\4\16\0\22\4\16\0\22\4"+
    "\16\0\15\4\1\0\3\4\17\0\64\4\43\0\1\4\4\0\1\4"+
    "\3\0\12\5\46\0\12\5\6\0\130\4\10\0\51\4\127\0\35\4"+
    "\51\0\12\5\36\4\2\0\5\4\u038b\0\154\4\224\0\234\4\4\0"+
    "\132\4\6\0\26\4\2\0\6\4\2\0\46\4\2\0\6\4\2\0"+
    "\10\4\1\0\1\4\1\0\1\4\1\0\1\4\1\0\37\4\2\0"+
    "\65\4\1\0\7\4\1\0\1\4\3\0\3\4\1\0\7\4\3\0"+
    "\4\4\2\0\6\4\4\0\15\4\5\0\3\4\1\0\7\4\164\0"+
    "\1\4\15\0\1\4\202\0\1\4\4\0\1\4\2\0\12\4\1\0"+
    "\1\4\3\0\5\4\6\0\1\4\1\0\1\4\1\0\1\4\1\0"+
    "\4\4\1\0\3\4\1\0\7\4\3\0\3\4\5\0\5\4\u0ebb\0"+
    "\2\4\52\0\5\4\5\0\2\4\4\0\126\4\6\0\3\4\1\0"+
    "\132\4\1\0\4\4\5\0\50\4\4\0\136\4\21\0\30\4\70\0"+
    "\20\4\u0200\0\u19b6\4\112\0\u51a6\4\132\0\u048d\4\u0773\0\u2ba4\4\u215c\0"+
    "\u012e\4\2\0\73\4\225\0\7\4\14\0\5\4\5\0\1\4\1\0"+
    "\12\4\1\0\15\4\1\0\5\4\1\0\1\4\1\0\2\4\1\0"+
    "\2\4\1\0\154\4\41\0\u016b\4\22\0\100\4\2\0\66\4\50\0"+
    "\14\4\164\0\5\4\1\0\207\4\23\0\12\5\7\0\32\4\6\0"+
    "\32\4\13\0\131\4\3\0\6\4\2\0\6\4\2\0\6\4\2\0"+
    "\3\4\43\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\1\5\1\2\1\6"+
    "\1\7\1\10\1\11\1\12\17\3\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\4\40\1\0\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\41\2\2\1\41\1\47\1\50\1\51"+
    "\1\52\2\10\1\53\5\3\1\54\1\55\1\56\3\3"+
    "\1\57\11\3\1\60\1\0\1\61\1\62\1\0\1\63"+
    "\1\0\1\64\1\65\1\66\1\67\1\70\1\71\1\72"+
    "\1\73\1\74\1\75\1\76\1\77\1\100\1\101\1\102"+
    "\1\41\5\0\1\103\4\3\1\104\5\3\1\105\1\3"+
    "\1\106\6\3\1\107\1\110\1\111\1\3\1\112\1\113"+
    "\1\114\1\115\1\116\1\117\1\41\1\0\2\3\1\120"+
    "\1\121\1\122\1\3\1\123\3\3\1\124\2\3\1\125"+
    "\3\3\1\126\1\3\1\127\1\130\3\3\1\131\1\132"+
    "\1\133\1\134\1\135\2\3\1\136\1\137\1\3\1\140"+
    "\1\141";

  private static int [] zzUnpackAction() {
    int [] result = new int[190];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\76\0\370\0\u0136\0\u0174"+
    "\0\u01b2\0\u01f0\0\u022e\0\u026c\0\u02aa\0\u02e8\0\76\0\u0326"+
    "\0\u0364\0\u03a2\0\u03e0\0\u041e\0\u045c\0\u049a\0\u04d8\0\u0516"+
    "\0\u0554\0\u0592\0\u05d0\0\u060e\0\u064c\0\u068a\0\u06c8\0\u0706"+
    "\0\76\0\u0744\0\76\0\u0782\0\u07c0\0\u07fe\0\u083c\0\u087a"+
    "\0\u08b8\0\u08f6\0\76\0\76\0\76\0\76\0\76\0\76"+
    "\0\76\0\76\0\76\0\76\0\u0934\0\u0972\0\u09b0\0\u09ee"+
    "\0\u0a2c\0\u0a6a\0\u0aa8\0\76\0\76\0\76\0\u0ae6\0\u0b24"+
    "\0\u0b62\0\u0ba0\0\76\0\76\0\u0bde\0\76\0\76\0\u0c1c"+
    "\0\76\0\u0c5a\0\u0c98\0\u0cd6\0\u0d14\0\u0d52\0\u0136\0\u0136"+
    "\0\u0136\0\u0d90\0\u0dce\0\u0e0c\0\u0e4a\0\u0e88\0\u0ec6\0\u0f04"+
    "\0\u0f42\0\u0f80\0\u0fbe\0\u0ffc\0\u103a\0\u1078\0\u0136\0\u10b6"+
    "\0\76\0\u10f4\0\u1132\0\76\0\u1170\0\76\0\76\0\76"+
    "\0\76\0\76\0\76\0\76\0\76\0\76\0\76\0\76"+
    "\0\76\0\76\0\76\0\76\0\u11ae\0\u11ec\0\u122a\0\u1268"+
    "\0\u12a6\0\u12e4\0\76\0\u1322\0\u1360\0\u139e\0\u13dc\0\u0136"+
    "\0\u141a\0\u1458\0\u1496\0\u14d4\0\u1512\0\76\0\u1550\0\u0136"+
    "\0\u158e\0\u15cc\0\u160a\0\u1648\0\u1686\0\u16c4\0\u0136\0\u0136"+
    "\0\u0136\0\u1702\0\u1740\0\u1740\0\76\0\76\0\76\0\76"+
    "\0\u177e\0\u11ae\0\u17bc\0\u17fa\0\u0136\0\u0136\0\u0136\0\u1838"+
    "\0\u0136\0\u1876\0\u18b4\0\u18f2\0\u0136\0\u1930\0\u196e\0\u0136"+
    "\0\u19ac\0\u19ea\0\u1a28\0\76\0\u1a66\0\u0136\0\u0136\0\u1aa4"+
    "\0\u1ae2\0\u1b20\0\u0136\0\u0136\0\u0136\0\u0136\0\u0136\0\u1b5e"+
    "\0\u1b9c\0\u0136\0\u0136\0\u1bda\0\u0136\0\u0136";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[190];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\7\1\5\1\11\1\10"+
    "\1\12\2\7\1\13\1\7\1\14\1\7\1\15\1\5"+
    "\1\7\1\16\1\17\1\20\1\7\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\2\7\1\27\1\7\1\30\1\31"+
    "\2\7\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\76\0\6\64\1\65\13\64\1\66"+
    "\76\64\1\67\52\64\1\0\1\6\6\0\1\6\2\0"+
    "\1\70\1\71\14\0\1\71\45\0\2\7\1\0\2\7"+
    "\2\0\3\7\1\0\1\7\1\0\1\7\2\0\1\7"+
    "\2\0\25\7\30\0\1\10\3\0\1\10\74\0\1\72"+
    "\13\0\1\73\1\74\33\0\1\75\2\0\1\76\14\0"+
    "\1\77\6\0\1\77\1\100\1\101\1\70\1\71\14\0"+
    "\1\71\12\0\1\101\32\0\1\102\6\0\1\102\2\0"+
    "\1\103\77\0\1\104\36\0\1\105\2\0\1\106\16\0"+
    "\7\15\1\0\7\15\1\107\1\110\55\15\57\0\1\111"+
    "\17\0\2\7\1\0\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\1\7\2\0\1\7\2\0\1\7\1\112\15\7"+
    "\1\113\5\7\26\0\2\7\1\0\2\7\2\0\3\7"+
    "\1\0\1\7\1\0\1\7\2\0\1\114\2\0\25\7"+
    "\26\0\2\7\1\0\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\1\7\2\0\1\7\2\0\12\7\1\115\3\7"+
    "\1\116\6\7\26\0\2\7\1\0\2\7\2\0\3\7"+
    "\1\0\1\7\1\0\1\7\2\0\1\7\2\0\2\7"+
    "\1\117\16\7\1\120\1\7\1\121\1\7\26\0\2\7"+
    "\1\0\2\7\2\0\3\7\1\0\1\7\1\0\1\7"+
    "\2\0\1\7\2\0\17\7\1\122\5\7\26\0\2\7"+
    "\1\0\2\7\2\0\3\7\1\0\1\7\1\0\1\7"+
    "\2\0\1\7\2\0\7\7\1\123\15\7\26\0\2\7"+
    "\1\0\2\7\2\0\3\7\1\0\1\7\1\0\1\7"+
    "\2\0\1\7\2\0\2\7\1\124\16\7\1\125\3\7"+
    "\26\0\2\7\1\0\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\1\7\2\0\1\7\2\0\5\7\1\126\17\7"+
    "\26\0\2\7\1\0\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\1\7\2\0\1\7\2\0\5\7\1\127\1\7"+
    "\1\130\15\7\26\0\2\7\1\0\2\7\2\0\3\7"+
    "\1\0\1\7\1\0\1\7\2\0\1\7\2\0\16\7"+
    "\1\131\6\7\26\0\2\7\1\0\2\7\2\0\3\7"+
    "\1\0\1\7\1\0\1\7\2\0\1\7\2\0\12\7"+
    "\1\132\12\7\26\0\2\7\1\0\2\7\2\0\3\7"+
    "\1\0\1\7\1\0\1\7\2\0\1\133\2\0\25\7"+
    "\26\0\2\7\1\0\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\1\7\2\0\1\7\2\0\7\7\1\134\15\7"+
    "\26\0\2\7\1\0\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\1\7\2\0\1\7\2\0\1\7\1\135\5\7"+
    "\1\136\15\7\26\0\2\7\1\0\2\7\2\0\3\7"+
    "\1\0\1\7\1\0\1\7\2\0\1\7\2\0\1\7"+
    "\1\137\23\7\55\0\1\140\26\0\1\141\70\0\1\142"+
    "\1\143\3\0\1\144\71\0\1\145\3\0\1\146\74\0"+
    "\1\147\1\150\75\0\1\151\75\0\1\152\1\153\74\0"+
    "\1\154\1\0\1\155\22\0\1\156\146\0\1\157\75\0"+
    "\1\160\40\0\1\161\61\0\1\162\75\0\1\163\70\0"+
    "\1\102\6\0\1\102\2\0\1\164\63\0\1\165\6\0"+
    "\1\165\4\0\1\165\40\0\1\165\17\0\7\72\1\0"+
    "\66\72\22\0\1\166\54\0\1\77\6\0\1\77\2\0"+
    "\1\167\1\71\14\0\1\71\45\0\2\100\5\0\1\100"+
    "\1\0\1\100\1\170\1\100\1\0\1\171\5\0\1\100"+
    "\4\0\1\100\1\171\1\100\10\0\1\100\2\0\2\100"+
    "\26\0\1\101\6\0\1\101\2\0\1\172\63\0\1\102"+
    "\6\0\1\102\3\0\1\71\14\0\1\71\120\0\1\173"+
    "\21\0\7\15\1\0\66\15\1\0\2\7\1\0\2\7"+
    "\2\0\3\7\1\0\1\7\1\0\1\7\2\0\1\7"+
    "\2\0\2\7\1\174\22\7\26\0\2\7\1\0\2\7"+
    "\2\0\3\7\1\0\1\7\1\0\1\7\2\0\1\7"+
    "\2\0\7\7\1\175\15\7\26\0\2\7\1\0\2\7"+
    "\2\0\3\7\1\0\1\7\1\0\1\7\2\0\1\7"+
    "\2\0\17\7\1\176\5\7\26\0\2\7\1\0\2\7"+
    "\2\0\3\7\1\0\1\7\1\0\1\7\2\0\1\177"+
    "\2\0\13\7\1\200\11\7\26\0\2\7\1\0\2\7"+
    "\2\0\3\7\1\0\1\7\1\0\1\7\2\0\1\7"+
    "\2\0\4\7\1\201\5\7\1\202\12\7\26\0\2\7"+
    "\1\0\2\7\2\0\3\7\1\0\1\7\1\0\1\7"+
    "\2\0\1\7\2\0\21\7\1\203\3\7\26\0\2\7"+
    "\1\0\2\7\2\0\3\7\1\0\1\7\1\0\1\7"+
    "\2\0\1\7\2\0\1\204\24\7\26\0\2\7\1\0"+
    "\2\7\2\0\3\7\1\0\1\7\1\0\1\7\2\0"+
    "\1\7\2\0\1\7\1\205\23\7\26\0\2\7\1\0"+
    "\2\7\2\0\3\7\1\0\1\7\1\0\1\7\2\0"+
    "\1\7\2\0\25\7\4\0\1\206\21\0\2\7\1\0"+
    "\2\7\2\0\3\7\1\0\1\7\1\0\1\7\2\0"+
    "\1\7\2\0\3\7\1\207\17\7\1\210\1\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\3\7\1\211\21\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\1\212\24\7\26\0\2\7"+
    "\1\0\2\7\2\0\3\7\1\0\1\7\1\0\1\7"+
    "\2\0\1\7\2\0\4\7\1\213\1\214\17\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\5\7\1\215\17\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\6\7\1\216\16\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\12\7\1\217\4\7\1\220"+
    "\5\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\12\7\1\221"+
    "\12\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\17\7\1\222"+
    "\5\7\53\0\1\223\16\0\1\224\107\0\1\225\70\0"+
    "\1\226\77\0\1\227\22\0\1\165\6\0\1\165\73\0"+
    "\1\230\70\0\1\102\6\0\1\102\66\0\2\231\5\0"+
    "\1\231\1\0\1\231\1\164\1\231\7\0\1\231\4\0"+
    "\1\231\1\0\1\231\10\0\1\231\2\0\2\231\26\0"+
    "\1\165\6\0\1\165\4\0\1\232\40\0\1\232\32\0"+
    "\1\164\63\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\3\7\1\233"+
    "\21\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\21\7\1\234"+
    "\3\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\17\7\1\235"+
    "\5\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\5\7\1\236"+
    "\17\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\21\7\1\237"+
    "\3\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\1\7\1\240"+
    "\23\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\5\7\1\241"+
    "\17\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\10\7\1\242"+
    "\14\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\2\7\1\243"+
    "\22\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\244\2\0\25\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\16\7\1\245\6\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\12\7\1\246\12\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\17\7\1\247\5\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\2\7\1\250\22\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\7\7\1\251\15\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\5\7\1\252\17\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\21\7\1\253\3\7\26\0"+
    "\2\254\1\0\2\254\2\0\3\254\1\0\1\254\1\0"+
    "\1\254\2\0\1\254\2\0\25\254\26\0\2\231\5\0"+
    "\1\231\1\0\1\231\1\0\1\231\1\0\1\171\5\0"+
    "\1\231\4\0\1\231\1\171\1\231\10\0\1\231\2\0"+
    "\2\231\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\4\7\1\255"+
    "\20\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\21\7\1\256"+
    "\3\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\15\7\1\257"+
    "\7\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\7\7\1\260"+
    "\15\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\13\7\1\261"+
    "\11\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\12\7\1\262"+
    "\12\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\1\7\1\263"+
    "\23\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\5\7\1\264"+
    "\17\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\10\7\1\265"+
    "\14\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\12\7\1\266"+
    "\12\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\5\7\1\267"+
    "\17\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\2\7\1\270"+
    "\22\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\11\7\1\271"+
    "\13\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\14\7\1\272"+
    "\10\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\7\2\0\2\7\1\273"+
    "\22\7\26\0\2\7\1\0\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\2\0\1\274\2\0\25\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\5\7\1\275\17\7\26\0"+
    "\2\7\1\0\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\2\0\1\7\2\0\5\7\1\276\17\7\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7192];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\2\0\1\11\11\1\1\11\21\1\1\11"+
    "\1\1\1\11\7\1\12\11\3\1\1\0\3\1\3\11"+
    "\4\1\2\11\1\1\2\11\1\1\1\11\26\1\1\0"+
    "\1\11\1\1\1\0\1\11\1\0\17\11\1\1\5\0"+
    "\1\11\12\1\1\11\16\1\4\11\1\1\1\0\21\1"+
    "\1\11\22\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[190];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private static final class State {
        final int state;

        public State(int state) {
            this.state = state;
        }

        @Override
        public String toString() {
            return "yystate = " + state ;
        }
    }

    private final Stack<State> states = new Stack<State>();

    private int commentStart;
    private int commentDepth;

    private void pushState(int state)
    {
        states.push(new State(yystate()));
        yybegin(state);
    }

    private void popState()
    {
        State state = states.pop();
        yybegin(state.state);
    }


  _NapileLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _NapileLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1324) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
      return;

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 9: 
          { return NapileTokens.MUL       ;
          }
        case 98: break;
        case 17: 
          { return NapileTokens.EQ        ;
          }
        case 99: break;
        case 80: 
          { return NapileTokens.NULL_KEYWORD ;
          }
        case 100: break;
        case 31: 
          { return NapileTokens.AT        ;
          }
        case 101: break;
        case 53: 
          { return NapileTokens.PLUSPLUS  ;
          }
        case 102: break;
        case 81: 
          { return NapileTokens.TRUE_KEYWORD ;
          }
        case 103: break;
        case 34: 
          { return NapileTokens.EOL_COMMENT;
          }
        case 104: break;
        case 67: 
          { return NapileTokens.DOUBLE_ARROW ;
          }
        case 105: break;
        case 27: 
          { return NapileTokens.LPAR      ;
          }
        case 106: break;
        case 29: 
          { return NapileTokens.SEMICOLON ;
          }
        case 107: break;
        case 2: 
          { return NapileTokens.INTEGER_LITERAL;
          }
        case 108: break;
        case 33: 
          { return NapileTokens.FLOAT_LITERAL;
          }
        case 109: break;
        case 85: 
          { return NapileTokens.WHEN_KEYWORD ;
          }
        case 110: break;
        case 7: 
          { return NapileTokens.MINUS     ;
          }
        case 111: break;
        case 43: 
          { return NapileTokens.MULTEQ    ;
          }
        case 112: break;
        case 25: 
          { return NapileTokens.LBRACE    ;
          }
        case 113: break;
        case 69: 
          { return NapileTokens.AS_SAFE;
          }
        case 114: break;
        case 71: 
          { return NapileTokens.VAR_KEYWORD ;
          }
        case 115: break;
        case 78: 
          { return NapileTokens.IDE_TEMPLATE_END    ;
          }
        case 116: break;
        case 50: 
          { return NapileTokens.LTLT      ;
          }
        case 117: break;
        case 37: 
          { return NapileTokens.DIVEQ     ;
          }
        case 118: break;
        case 3: 
          { return NapileTokens.IDENTIFIER;
          }
        case 119: break;
        case 76: 
          { return NapileTokens.LTLTEQ    ;
          }
        case 120: break;
        case 38: 
          { return NapileTokens.INJECTION_START;
          }
        case 121: break;
        case 68: 
          { return NapileTokens.TRY_KEYWORD ;
          }
        case 122: break;
        case 55: 
          { return NapileTokens.EQEQ      ;
          }
        case 123: break;
        case 93: 
          { return NapileTokens.FALSE_KEYWORD ;
          }
        case 124: break;
        case 56: 
          { return NapileTokens.ANDEQ     ;
          }
        case 125: break;
        case 16: 
          { return NapileTokens.PLUS      ;
          }
        case 126: break;
        case 13: 
          { return NapileTokens.HASH      ;
          }
        case 127: break;
        case 54: 
          { return NapileTokens.PLUSEQ    ;
          }
        case 128: break;
        case 30: 
          { return NapileTokens.COMMA     ;
          }
        case 129: break;
        case 14: 
          { return NapileTokens.GT        ;
          }
        case 130: break;
        case 8: 
          { return NapileTokens.STRING_LITERAL;
          }
        case 131: break;
        case 28: 
          { return NapileTokens.RPAR      ;
          }
        case 132: break;
        case 91: 
          { return NapileTokens.BREAK_KEYWORD ;
          }
        case 133: break;
        case 97: 
          { return NapileTokens.CONTINUE_KEYWORD ;
          }
        case 134: break;
        case 12: 
          { return NapileTokens.LT        ;
          }
        case 135: break;
        case 61: 
          { return NapileTokens.XOREQ     ;
          }
        case 136: break;
        case 94: 
          { return NapileTokens.ANONYM_KEYWORD ;
          }
        case 137: break;
        case 20: 
          { return NapileTokens.COLON     ;
          }
        case 138: break;
        case 46: 
          { return NapileTokens.IF_KEYWORD ;
          }
        case 139: break;
        case 41: 
          { return NapileTokens.ARROW     ;
          }
        case 140: break;
        case 23: 
          { return NapileTokens.LBRACKET  ;
          }
        case 141: break;
        case 36: 
          { pushState(DOC_COMMENT);
    commentDepth = 0;
    commentStart = getTokenStart();
          }
        case 142: break;
        case 74: 
          { return NapileTokens.NOT_IN;
          }
        case 143: break;
        case 19: 
          { return NapileTokens.OR        ;
          }
        case 144: break;
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 145: break;
        case 26: 
          { return NapileTokens.RBRACE    ;
          }
        case 146: break;
        case 57: 
          { return NapileTokens.ANDAND    ;
          }
        case 147: break;
        case 96: 
          { return NapileTokens.PACKAGE_KEYWORD ;
          }
        case 148: break;
        case 10: 
          { return NapileTokens.TILDE     ;
          }
        case 149: break;
        case 64: 
          { if (commentDepth > 0) {
            commentDepth--;
        }
        else {
             int state = yystate();
             popState();
             zzStartRead = commentStart;
             return NapileTokens.BLOCK_COMMENT;
        }
          }
        case 150: break;
        case 51: 
          { return NapileTokens.LTEQ      ;
          }
        case 151: break;
        case 42: 
          { return NapileTokens.MINUSEQ   ;
          }
        case 152: break;
        case 77: 
          { return NapileTokens.IDE_TEMPLATE_START    ;
          }
        case 153: break;
        case 82: 
          { return NapileTokens.THIS_KEYWORD ;
          }
        case 154: break;
        case 45: 
          { return NapileTokens.IS_KEYWORD ;
          }
        case 155: break;
        case 65: 
          { popState();
		zzStartRead = commentStart;
		return NapileTokens.DOC_COMMENT;
          }
        case 156: break;
        case 40: 
          { return NapileTokens.MINUSMINUS;
          }
        case 157: break;
        case 86: 
          { yypushback(3); return NapileTokens.EXCL;
          }
        case 158: break;
        case 35: 
          { pushState(BLOCK_COMMENT);
    commentDepth = 0;
    commentStart = getTokenStart();
          }
        case 159: break;
        case 52: 
          { return NapileTokens.GTEQ      ;
          }
        case 160: break;
        case 5: 
          { return NapileTokens.DIV       ;
          }
        case 161: break;
        case 44: 
          { return NapileTokens.IN_KEYWORD ;
          }
        case 162: break;
        case 58: 
          { return NapileTokens.OREQ      ;
          }
        case 163: break;
        case 11: 
          { return NapileTokens.EXCL      ;
          }
        case 164: break;
        case 75: 
          { return NapileTokens.NOT_IS;
          }
        case 165: break;
        case 49: 
          { return NapileTokens.EXCLEQ    ;
          }
        case 166: break;
        case 90: 
          { return NapileTokens.WHILE_KEYWORD ;
          }
        case 167: break;
        case 83: 
          { return NapileTokens.ELSE_KEYWORD ;
          }
        case 168: break;
        case 18: 
          { return NapileTokens.AND       ;
          }
        case 169: break;
        case 15: 
          { return NapileTokens.QUEST     ;
          }
        case 170: break;
        case 60: 
          { return NapileTokens.INJECTION_STOP;
          }
        case 171: break;
        case 22: 
          { return NapileTokens.PERC      ;
          }
        case 172: break;
        case 47: 
          { return NapileTokens.AS_KEYWORD ;
          }
        case 173: break;
        case 87: 
          { return NapileTokens.CLASS_KEYWORD ;
          }
        case 174: break;
        case 62: 
          { return NapileTokens.PERCEQ    ;
          }
        case 175: break;
        case 95: 
          { return NapileTokens.RETURN_KEYWORD ;
          }
        case 176: break;
        case 89: 
          { return NapileTokens.MACRO_KEYWORD ;
          }
        case 177: break;
        case 63: 
          { commentDepth++;
          }
        case 178: break;
        case 88: 
          { return NapileTokens.THROW_KEYWORD ;
          }
        case 179: break;
        case 92: 
          { return NapileTokens.SUPER_KEYWORD ;
          }
        case 180: break;
        case 72: 
          { return NapileTokens.VAL_KEYWORD ;
          }
        case 181: break;
        case 48: 
          { return NapileTokens.DO_KEYWORD ;
          }
        case 182: break;
        case 70: 
          { return NapileTokens.REF_KEYWORD ;
          }
        case 183: break;
        case 24: 
          { return NapileTokens.RBRACKET  ;
          }
        case 184: break;
        case 21: 
          { return NapileTokens.XOR       ;
          }
        case 185: break;
        case 59: 
          { return NapileTokens.OROR      ;
          }
        case 186: break;
        case 66: 
          { yypushback(2); return NapileTokens.INTEGER_LITERAL;
          }
        case 187: break;
        case 39: 
          { return NapileTokens.RANGE     ;
          }
        case 188: break;
        case 84: 
          { return NapileTokens.METH_KEYWORD ;
          }
        case 189: break;
        case 4: 
          { return NapileTokens.WHITE_SPACE;
          }
        case 190: break;
        case 79: 
          { return NapileTokens.BLOCK_COMMENT;
          }
        case 191: break;
        case 6: 
          { return NapileTokens.DOT       ;
          }
        case 192: break;
        case 73: 
          { return NapileTokens.FOR_KEYWORD ;
          }
        case 193: break;
        case 32: 
          { 
          }
        case 194: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case BLOCK_COMMENT: {
              int state = yystate();
        popState();
        zzStartRead = commentStart;
        return NapileTokens.BLOCK_COMMENT;
            }
            case 191: break;
            case DOC_COMMENT: {
              popState();
        zzStartRead = commentStart;
        return NapileTokens.DOC_COMMENT;
            }
            case 192: break;
            default:
            return null;
            }
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
